# Generated by Django 5.1.6 on 2025-02-21 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_question_image_remove_question_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='game_pin',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='result',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
