# Generated by Django 5.1.6 on 2025-02-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_quiz_game_pin_remove_quiz_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='answers/photos/'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='quiz/logos/'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_count',
            field=models.IntegerField(default=0, help_text='Кількість питань'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_timer',
            field=models.IntegerField(default=60, help_text='Загальний таймер для всіх питань (в секундах)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=30, help_text='Таймер для питання (в секундах)'),
        ),
    ]
