# Generated by Django 5.1.6 on 2025-02-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_answer_photo_quiz_logo_quiz_question_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='total_time',
            field=models.IntegerField(default=60),
        ),
    ]
